@rem
@rem Copyright © 2015-2021 the original authors.
@rem
@rem Gradle start up script for Windows generated by Gradle.
@rem

@echo off
set APP_HOME=%~dp0
set CLASSPATH=%APP_HOME%gradle\wrapper\gradle-wrapper.jar

if not exist "%CLASSPATH%" (
  echo Missing gradle\wrapper\gradle-wrapper.jar — run 'gradle wrapper' or open in Android Studio. 1>&2
  exit /b 1
)

java -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
