#!/usr/bin/env bash
# Load release-signing environment variables from android/app/release-key.properties
# into the current shell so a LOCAL `gradle assembleRelease` can sign the APK.
#
#   source scripts/load_release_env.sh
#   cd android && gradle assembleRelease
#
# Requires: android/app/release-key.jks + release-key.properties (generated by
# `keytool`, see BUILD.md §5). Both are gitignored and never committed.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROPS="$DIR/android/app/release-key.properties"

if [[ ! -f "$PROPS" ]]; then
  echo "ERROR: $PROPS not found. Generate the keystore first (see BUILD.md §5)." >&2
  exit 1
fi

export KEYSTORE_PATH="$DIR/android/app/release-key.jks"
while IFS='=' read -r k v; do
  [[ -z "$k" || "$k" == \#* ]] && continue
  export "$k=$v"
done < "$PROPS"

echo "Release-signing env loaded:"
echo "  KEYSTORE_PATH=$KEYSTORE_PATH"
echo "  KEY_ALIAS=$KEY_ALIAS"
echo "  KEY_PASSWORD / KEYSTORE_PASSWORD set (hidden)"
